name: Check Build

on:
  pull_request:
    branches: [ main ]

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Check for uncommitted build changes
      run: |
        if [ -n "$(git diff --name-only)" ]; then
          echo "❌ Build output is not up to date. The following files have changes:"
          git diff --name-only
          echo ""
          echo "Please run 'npm run build' locally and commit the changes."
          exit 1
        else
          echo "✅ Build output is up to date!"
        fi

    - name: Verify main.js exists and is not empty
      run: |
        if [ ! -f "main.js" ]; then
          echo "❌ main.js does not exist!"
          exit 1
        fi
        if [ ! -s "main.js" ]; then
          echo "❌ main.js is empty!"
          exit 1
        fi
        echo "✅ main.js exists and has content"